// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.github.fileBridge.common.proto;

public final class EventOuterClass {
  private EventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string output = 1;</code>
     * @return The output.
     */
    java.lang.String getOutput();
    /**
     * <code>string output = 1;</code>
     * @return The bytes for output.
     */
    com.google.protobuf.ByteString
        getOutputBytes();

    /**
     * <code>string absPath = 2;</code>
     * @return The absPath.
     */
    java.lang.String getAbsPath();
    /**
     * <code>string absPath = 2;</code>
     * @return The bytes for absPath.
     */
    com.google.protobuf.ByteString
        getAbsPathBytes();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */
    int getStructCount();
    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */
    boolean containsStruct(
        java.lang.String key);
    /**
     * Use {@link #getStructMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getStruct();
    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getStructMap();
    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */

    /* nullable */
java.lang.String getStructOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */

    java.lang.String getStructOrThrow(
        java.lang.String key);

    /**
     * <code>string id = 5;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 5;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Event)
      EventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
      output_ = "";
      absPath_ = "";
      content_ = "";
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Event();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.fileBridge.common.proto.EventOuterClass.internal_static_Event_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetStruct();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.fileBridge.common.proto.EventOuterClass.internal_static_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.fileBridge.common.proto.EventOuterClass.Event.class, com.github.fileBridge.common.proto.EventOuterClass.Event.Builder.class);
    }

    public static final int OUTPUT_FIELD_NUMBER = 1;
    private volatile java.lang.Object output_;
    /**
     * <code>string output = 1;</code>
     * @return The output.
     */
    @java.lang.Override
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        output_ = s;
        return s;
      }
    }
    /**
     * <code>string output = 1;</code>
     * @return The bytes for output.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ABSPATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object absPath_;
    /**
     * <code>string absPath = 2;</code>
     * @return The absPath.
     */
    @java.lang.Override
    public java.lang.String getAbsPath() {
      java.lang.Object ref = absPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        absPath_ = s;
        return s;
      }
    }
    /**
     * <code>string absPath = 2;</code>
     * @return The bytes for absPath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAbsPathBytes() {
      java.lang.Object ref = absPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        absPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRUCT_FIELD_NUMBER = 4;
    private static final class StructDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.github.fileBridge.common.proto.EventOuterClass.internal_static_Event_StructEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> struct_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetStruct() {
      if (struct_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StructDefaultEntryHolder.defaultEntry);
      }
      return struct_;
    }

    public int getStructCount() {
      return internalGetStruct().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */

    @java.lang.Override
    public boolean containsStruct(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStruct().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStructMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getStruct() {
      return getStructMap();
    }
    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getStructMap() {
      return internalGetStruct().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getStructOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStruct().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; struct = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getStructOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStruct().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 5;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 5;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(output_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, output_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(absPath_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, absPath_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetStruct(),
          StructDefaultEntryHolder.defaultEntry,
          4);
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(output_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, output_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(absPath_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, absPath_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetStruct().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        struct__ = StructDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, struct__);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.fileBridge.common.proto.EventOuterClass.Event)) {
        return super.equals(obj);
      }
      com.github.fileBridge.common.proto.EventOuterClass.Event other = (com.github.fileBridge.common.proto.EventOuterClass.Event) obj;

      if (!getOutput()
          .equals(other.getOutput())) return false;
      if (!getAbsPath()
          .equals(other.getAbsPath())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!internalGetStruct().equals(
          other.internalGetStruct())) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
      hash = (37 * hash) + ABSPATH_FIELD_NUMBER;
      hash = (53 * hash) + getAbsPath().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (!internalGetStruct().getMap().isEmpty()) {
        hash = (37 * hash) + STRUCT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStruct().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.fileBridge.common.proto.EventOuterClass.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.fileBridge.common.proto.EventOuterClass.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Event)
        com.github.fileBridge.common.proto.EventOuterClass.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.fileBridge.common.proto.EventOuterClass.internal_static_Event_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetStruct();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableStruct();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.fileBridge.common.proto.EventOuterClass.internal_static_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.fileBridge.common.proto.EventOuterClass.Event.class, com.github.fileBridge.common.proto.EventOuterClass.Event.Builder.class);
      }

      // Construct using com.github.fileBridge.common.proto.EventOuterClass.Event.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        output_ = "";

        absPath_ = "";

        content_ = "";

        internalGetMutableStruct().clear();
        id_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.fileBridge.common.proto.EventOuterClass.internal_static_Event_descriptor;
      }

      @java.lang.Override
      public com.github.fileBridge.common.proto.EventOuterClass.Event getDefaultInstanceForType() {
        return com.github.fileBridge.common.proto.EventOuterClass.Event.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.fileBridge.common.proto.EventOuterClass.Event build() {
        com.github.fileBridge.common.proto.EventOuterClass.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.fileBridge.common.proto.EventOuterClass.Event buildPartial() {
        com.github.fileBridge.common.proto.EventOuterClass.Event result = new com.github.fileBridge.common.proto.EventOuterClass.Event(this);
        int from_bitField0_ = bitField0_;
        result.output_ = output_;
        result.absPath_ = absPath_;
        result.content_ = content_;
        result.struct_ = internalGetStruct();
        result.struct_.makeImmutable();
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.fileBridge.common.proto.EventOuterClass.Event) {
          return mergeFrom((com.github.fileBridge.common.proto.EventOuterClass.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.fileBridge.common.proto.EventOuterClass.Event other) {
        if (other == com.github.fileBridge.common.proto.EventOuterClass.Event.getDefaultInstance()) return this;
        if (!other.getOutput().isEmpty()) {
          output_ = other.output_;
          onChanged();
        }
        if (!other.getAbsPath().isEmpty()) {
          absPath_ = other.absPath_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        internalGetMutableStruct().mergeFrom(
            other.internalGetStruct());
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                output_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                absPath_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                content_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                struct__ = input.readMessage(
                    StructDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableStruct().getMutableMap().put(
                    struct__.getKey(), struct__.getValue());
                break;
              } // case 34
              case 42: {
                id_ = input.readStringRequireUtf8();

                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object output_ = "";
      /**
       * <code>string output = 1;</code>
       * @return The output.
       */
      public java.lang.String getOutput() {
        java.lang.Object ref = output_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          output_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string output = 1;</code>
       * @return The bytes for output.
       */
      public com.google.protobuf.ByteString
          getOutputBytes() {
        java.lang.Object ref = output_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          output_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string output = 1;</code>
       * @param value The output to set.
       * @return This builder for chaining.
       */
      public Builder setOutput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        output_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string output = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOutput() {
        
        output_ = getDefaultInstance().getOutput();
        onChanged();
        return this;
      }
      /**
       * <code>string output = 1;</code>
       * @param value The bytes for output to set.
       * @return This builder for chaining.
       */
      public Builder setOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        output_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object absPath_ = "";
      /**
       * <code>string absPath = 2;</code>
       * @return The absPath.
       */
      public java.lang.String getAbsPath() {
        java.lang.Object ref = absPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          absPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string absPath = 2;</code>
       * @return The bytes for absPath.
       */
      public com.google.protobuf.ByteString
          getAbsPathBytes() {
        java.lang.Object ref = absPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          absPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string absPath = 2;</code>
       * @param value The absPath to set.
       * @return This builder for chaining.
       */
      public Builder setAbsPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        absPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string absPath = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAbsPath() {
        
        absPath_ = getDefaultInstance().getAbsPath();
        onChanged();
        return this;
      }
      /**
       * <code>string absPath = 2;</code>
       * @param value The bytes for absPath to set.
       * @return This builder for chaining.
       */
      public Builder setAbsPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        absPath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> struct_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetStruct() {
        if (struct_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StructDefaultEntryHolder.defaultEntry);
        }
        return struct_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableStruct() {
        onChanged();;
        if (struct_ == null) {
          struct_ = com.google.protobuf.MapField.newMapField(
              StructDefaultEntryHolder.defaultEntry);
        }
        if (!struct_.isMutable()) {
          struct_ = struct_.copy();
        }
        return struct_;
      }

      public int getStructCount() {
        return internalGetStruct().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; struct = 4;</code>
       */

      @java.lang.Override
      public boolean containsStruct(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetStruct().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStructMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getStruct() {
        return getStructMap();
      }
      /**
       * <code>map&lt;string, string&gt; struct = 4;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getStructMap() {
        return internalGetStruct().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; struct = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getStructOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetStruct().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; struct = 4;</code>
       */
      @java.lang.Override

      public java.lang.String getStructOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetStruct().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStruct() {
        internalGetMutableStruct().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; struct = 4;</code>
       */

      public Builder removeStruct(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableStruct().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableStruct() {
        return internalGetMutableStruct().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; struct = 4;</code>
       */
      public Builder putStruct(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableStruct().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; struct = 4;</code>
       */

      public Builder putAllStruct(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableStruct().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 5;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Event)
    }

    // @@protoc_insertion_point(class_scope:Event)
    private static final com.github.fileBridge.common.proto.EventOuterClass.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.fileBridge.common.proto.EventOuterClass.Event();
    }

    public static com.github.fileBridge.common.proto.EventOuterClass.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      @java.lang.Override
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.fileBridge.common.proto.EventOuterClass.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_StructEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_StructEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\"\230\001\n\005Event\022\016\n\006output\030\001 \001(\t\022" +
      "\017\n\007absPath\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\"\n\006str" +
      "uct\030\004 \003(\0132\022.Event.StructEntry\022\n\n\002id\030\005 \001(" +
      "\t\032-\n\013StructEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001B$\n\"com.github.fileBridge.common" +
      ".protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_descriptor,
        new java.lang.String[] { "Output", "AbsPath", "Content", "Struct", "Id", });
    internal_static_Event_StructEntry_descriptor =
      internal_static_Event_descriptor.getNestedTypes().get(0);
    internal_static_Event_StructEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_StructEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
