// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventService.proto

package com.github.fileBridge.common.proto;

public final class EventServiceOuterClass {
  private EventServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022EventService.proto\032\013Event.proto\032\tRes.p" +
      "roto2L\n\014EventService\022\035\n\tpushAsync\022\006.Even" +
      "t\032\004.Res\"\000(\001\022\035\n\013healthCheck\022\006.Event\032\004.Res" +
      "\"\000B$\n\"com.github.fileBridge.common.proto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.fileBridge.common.proto.EventOuterClass.getDescriptor(),
          com.github.fileBridge.common.proto.ResOuterClass.getDescriptor(),
        });
    com.github.fileBridge.common.proto.EventOuterClass.getDescriptor();
    com.github.fileBridge.common.proto.ResOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
